# Generated by Django 2.2.19 on 2021-04-19 15:47

from django.db import migrations


def populate_plans(apps, schema_editor):
    Plan = apps.get_model("payments", "Plan")
    plans = [
        {"name": "Free", "description": "Free Plan", "price": 0},
        {"name": "Standard", "description": "Standard Plan", "price": 10},
        {"name": "Pro", "description": "Pro Plan", "price": 25}
    ]
    Plan.objects.bulk_create([Plan(**plan_data) for plan_data in plans])


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_plans)
    ]
